import { Service, NotificationChannel } from './types';
import { Activity, Cloud, Music, Play, Box, Database, Video } from 'lucide-react';

export const SERVICE_COLORS = {
  vercel: '#000000',
  supabase: '#3ECF8E',
  openai: '#10A37F',
  cursor: '#2563EB', // Blue
  claude: '#D97757', // Terracotta
  appwrite: '#FD366E',
  namecheap: '#DE3723',
  gemini: '#4285F4', // Google Blue
  resend: '#171717', // Dark Grey
  railway: '#B026FF',
};

// Helper for consistent logos
const getLogo = (domain: string) => `https://logo.clearbit.com/${domain}`;

export const MOCK_SERVICES: Service[] = [
  {
    id: '1',
    name: 'Vercel',
    category: 'Hosting',
    price: 20.00,
    currency: '$',
    billingCycle: 'monthly',
    nextPayment: '2024-03-01',
    color: SERVICE_COLORS.vercel,
    logo: getLogo('vercel.com'),
    usageMetric: 'Bandwidth',
    usageCurrent: 85,
    usageLimit: 100,
    usageUnit: 'GB',
    status: 'active',
    connected: true,
  },
  {
    id: '2',
    name: 'OpenAI API',
    category: 'AI Models',
    price: 0, // Pay as you go
    currency: '$',
    billingCycle: 'monthly',
    nextPayment: '2024-03-05',
    color: SERVICE_COLORS.openai,
    logo: getLogo('openai.com'),
    usageMetric: 'Spending Limit',
    usageCurrent: 84.20,
    usageLimit: 120.00,
    usageUnit: '$',
    status: 'active',
    connected: true,
  },
  {
    id: '3',
    name: 'Supabase',
    category: 'Backend',
    price: 25.00,
    currency: '$',
    billingCycle: 'monthly',
    nextPayment: '2024-02-28',
    color: SERVICE_COLORS.supabase, 
    logo: getLogo('supabase.com'),
    usageMetric: 'Database Size',
    usageCurrent: 6.2,
    usageLimit: 8.0,
    usageUnit: 'GB',
    status: 'active',
    connected: true,
  },
  {
    id: '4',
    name: 'Cursor',
    category: 'Tools',
    price: 20.00,
    currency: '$',
    billingCycle: 'monthly',
    nextPayment: '2024-03-10',
    color: SERVICE_COLORS.cursor,
    logo: getLogo('cursor.sh'),
    status: 'active',
    connected: true,
  },
  {
    id: '5',
    name: 'Claude API',
    category: 'AI Models',
    price: 0,
    currency: '$',
    billingCycle: 'monthly',
    nextPayment: '2024-03-15',
    color: SERVICE_COLORS.claude, 
    logo: getLogo('anthropic.com'),
    usageMetric: 'Spend Limit',
    usageCurrent: 12.50,
    usageLimit: 50.00,
    usageUnit: '$',
    status: 'active',
    connected: true,
  },
  {
    id: '6',
    name: 'Resend',
    category: 'Email',
    price: 20.00,
    currency: '$',
    billingCycle: 'monthly',
    nextPayment: '2024-03-02',
    color: SERVICE_COLORS.resend,
    logo: getLogo('resend.com'),
    usageMetric: 'Emails',
    usageCurrent: 45000,
    usageLimit: 50000,
    usageUnit: 'sent',
    status: 'active',
    connected: true,
  },
  {
    id: '7',
    name: 'Namecheap',
    category: 'Domains',
    price: 9.88,
    currency: '$',
    billingCycle: 'yearly',
    nextPayment: '2024-06-12',
    color: SERVICE_COLORS.namecheap,
    logo: getLogo('namecheap.com'),
    status: 'active',
    connected: true,
  },
  {
    id: '8',
    name: 'Appwrite',
    category: 'Backend',
    price: 15.00,
    currency: '$',
    billingCycle: 'monthly',
    nextPayment: '2024-03-20',
    color: SERVICE_COLORS.appwrite,
    logo: getLogo('appwrite.io'),
    usageMetric: 'Bandwidth',
    usageCurrent: 120,
    usageLimit: 1000,
    usageUnit: 'GB',
    status: 'active',
    connected: true,
  },
   {
    id: '9',
    name: 'Gemini API',
    category: 'AI Models',
    price: 0,
    currency: '$',
    billingCycle: 'monthly',
    nextPayment: '2024-03-01',
    color: SERVICE_COLORS.gemini,
    logo: getLogo('google.com'), // Fallback as gemini specific url might be tricky, usually google generic
    usageMetric: 'Queries',
    usageCurrent: 15430,
    usageLimit: 100000,
    usageUnit: 'req',
    status: 'active',
    connected: true,
  },
];

export const MOCK_NOTIFICATIONS: NotificationChannel[] = [
  { id: '1', type: 'push', name: 'Push Notifications', detail: 'Instant alerts for API limits', enabled: true },
  { id: '2', type: 'email', name: 'Email Reports', detail: 'Weekly spend summaries', enabled: true },
  { id: '3', type: 'slack', name: 'Slack Webhook', detail: '#dev-ops channel', enabled: false },
];