import { Service, NotificationChannel } from './types';
import { Activity, Cloud, Music, Play, Box, Database, Video } from 'lucide-react';

export const SERVICE_COLORS: Record<string, string> = {
  vercel: '#000000',
  supabase: '#3ECF8E',
  openai: '#10A37F',
  cursor: '#14120B',
  claude: '#D97757', // Terracotta
  appwrite: '#FD366E',
  namecheap: '#DE3723',
  gemini: '#4285F4', // Google Blue
  resend: '#171717', // Dark Grey
  railway: '#B026FF',
  render: '#46E3B7',
  cloudflare: '#F38020',
  planetscale: '#000000',
  neon: '#00E5FF',
  turso: '#00E5FF',
  convex: '#FFD700',
  drizzle: '#FF6B6B',
  stripe: '#635BFF',
  lemonsqueezy: '#FFD700',
  paddle: '#00C4CC',
  revenuecat: '#00C4CC',
  inngest: '#00E5FF',
  upstash: '#00E5FF',
  workos: '#635BFF',
  clerk: '#000000',
  anthropic: '#D97757',
  googlegemini: '#4285F4',
  v0: '#000000',
  v0dev: '#000000',
  lovable: '#00E5FF',
  linear: '#5E6AD2',
  notion: '#000000',
  figma: '#F24E1E',
  excalidraw: '#000000',
  tldraw: '#000000',
  sentry: '#362D59',
  posthog: '#E02424',
  betterstack: '#000000',
  fathom: '#000000',
  plausible: '#5850EC',
  crisp: '#FF652F',
  loops: '#000000',
  dockerdesktop: '#2496ED',
  jetbrains: '#000000',
  postman: '#FF6C37',
  insomnia: '#4000BF',
  tableplus: '#000000',
  expo: '#000020',
  fastlane: '#00F200',
  doppler: '#00C4CC',
  gitlab: '#FC6D26',
  bitbucket: '#0052CC',
  githubcopilot: '#000000',
};

export const MOCK_SERVICES: Service[] = [
  {
    id: '1',
    name: 'Vercel',
    category: 'Hosting',
    price: 20.00,
    currency: '$',
    billingCycle: 'monthly',
    nextPayment: '2024-03-01',
    color: SERVICE_COLORS.vercel,
    logo: '/logos/vercel.svg',
    usageMetric: 'Bandwidth',
    usageCurrent: 85,
    usageLimit: 100,
    usageUnit: 'GB',
    status: 'active',
    connected: true,
  },
  {
    id: '2',
    name: 'OpenAI API',
    category: 'AI Models',
    price: 0, // Pay as you go
    currency: '$',
    billingCycle: 'monthly',
    nextPayment: '2024-03-05',
    color: SERVICE_COLORS.openai,
    logo: '/logos/openai.svg',
    usageMetric: 'Spending Limit',
    usageCurrent: 84.20,
    usageLimit: 120.00,
    usageUnit: '$',
    status: 'active',
    connected: true,
  },
  {
    id: '3',
    name: 'Supabase',
    category: 'Backend',
    price: 25.00,
    currency: '$',
    billingCycle: 'monthly',
    nextPayment: '2024-02-28',
    color: SERVICE_COLORS.supabase, 
    logo: '/logos/supabase.svg',
    usageMetric: 'Database Size',
    usageCurrent: 6.2,
    usageLimit: 8.0,
    usageUnit: 'GB',
    status: 'active',
    connected: true,
  },
  {
    id: '4',
    name: 'Cursor',
    category: 'Tools',
    price: 20.00,
    currency: '$',
    billingCycle: 'monthly',
    nextPayment: '2024-03-10',
    color: SERVICE_COLORS.cursor,
    logo: '/logos/cursor.svg',
    status: 'active',
    connected: true,
  },
  {
    id: '5',
    name: 'Claude API',
    category: 'AI Models',
    price: 0,
    currency: '$',
    billingCycle: 'monthly',
    nextPayment: '2024-03-15',
    color: SERVICE_COLORS.claude, 
    logo: '/logos/anthropic.svg',
    usageMetric: 'Spend Limit',
    usageCurrent: 12.50,
    usageLimit: 50.00,
    usageUnit: '$',
    status: 'active',
    connected: true,
  },
  {
    id: '6',
    name: 'Resend',
    category: 'Email',
    price: 20.00,
    currency: '$',
    billingCycle: 'monthly',
    nextPayment: '2024-03-02',
    color: SERVICE_COLORS.resend,
    logo: '/logos/resend.svg',
    usageMetric: 'Emails',
    usageCurrent: 45000,
    usageLimit: 50000,
    usageUnit: 'sent',
    status: 'active',
    connected: true,
  },
  {
    id: '7',
    name: 'Namecheap',
    category: 'Domains',
    price: 9.88,
    currency: '$',
    billingCycle: 'yearly',
    nextPayment: '2024-06-12',
    color: SERVICE_COLORS.namecheap,
    logo: '/logos/namecheap.svg',
    status: 'active',
    connected: true,
  },
  {
    id: '8',
    name: 'Appwrite',
    category: 'Backend',
    price: 15.00,
    currency: '$',
    billingCycle: 'monthly',
    nextPayment: '2024-03-20',
    color: SERVICE_COLORS.appwrite,
    logo: '/logos/appwrite.svg',
    usageMetric: 'Bandwidth',
    usageCurrent: 120,
    usageLimit: 1000,
    usageUnit: 'GB',
    status: 'active',
    connected: true,
  },
   {
    id: '9',
    name: 'Gemini API',
    category: 'AI Models',
    price: 0,
    currency: '$',
    billingCycle: 'monthly',
    nextPayment: '2024-03-01',
    color: SERVICE_COLORS.gemini,
    logo: '/logos/googlegemini.svg',
    usageMetric: 'Queries',
    usageCurrent: 15430,
    usageLimit: 100000,
    usageUnit: 'req',
    status: 'active',
    connected: true,
  },
];

export const MOCK_NOTIFICATIONS: NotificationChannel[] = [
  { id: '1', type: 'push', name: 'Push Notifications', detail: 'Instant alerts for API limits', enabled: true },
  { id: '2', type: 'email', name: 'Email Reports', detail: 'Weekly spend summaries', enabled: true },
  { id: '3', type: 'slack', name: 'Slack Webhook', detail: '#dev-ops channel', enabled: false },
];